### ISSUE TITLE
How to install Userify enterprise, missing packages?

### ISSUE THREAD

**Issue by noisy** [userify/enterprise#1]
On https://userify.com/enterprise/ I didn't found any information that two additional system packages are required: `libffi-dev`, `libssl-dev`, and one non mentioned in description python package: `pyopenssl`. I am not sure on how many other systems this can be a problem.

And about python packages, maybe keeping list inside directory with sources, in requirements.txt will help keep everything in sync.

**Comment by jamiesonbecker** [comment]
Excellent - thanks Krz, we'll get these added to the instructions and will add a requirements.txt as well!

**Comment by jamiesonbecker** [comment]
Updated documentation and added requirements.txt. Thanks for the bug report! :)

**Comment by jamiesonbecker** [comment]
New, massively changed version coming soon. Please email for specifics.
